metric_server = "http://localhost:8000" # default
scenarios_dir = "./scenarios"           # default
telegraf_conf = "./telegraf.conf"       # default
interval = "5s"                         # default

[application]
processes.docker = ["accuheat_client_db"]
processes.metal = ["accuheat_client"]

[scenario_runner]
cpu_tdp = 23

