debug_level = "info" # Optional - defaults to "info"
#metrics_server_url = "http://cardamon.rootandbranch.io" # Optional - assumes local db if not specifed

#[[processes]]
#type = "docker"
#name = "db"                      # Required - must be unique among ALL processes
#containers = ["postgres"]        # Required
#up = "docker compose up -d" # Required
#down = "docker down"

[[processes]]
type = "baremetal"
name = "test"                                               # Required
up = "bash -c \"while true; do shuf -i 0-1337 -n 1; done\"" # Required
down = "kill {pid}"
redirect.to = "file"

[[scenarios]]
name = "basket_10"                    # Required
desc = "Adds ten items to the basket" # Optional 
command = "sleep 15"                  # Required - commands for running scenarios
iterations = 2                        # Optional - defaults to 1
processes = ["test"]                  # Required - prepend process name with `_` to ignore

[[observations]]
name = "obs_1"            # Required
scenarios = ["basket_10"] # Required
