[config]
mode = "dir" 
directory = "scenarios"
command = "node {file}"

# mode = "default"
#commands = ["node scenarios/index.js", "node scenarios/main.js"]
# mode = "dir"
# directory = "scenarios"
# command = "node run {file}


## Below is non-functional pseudocode
metric_server = "http://localhost:8000" # default
scenarios_dir = "./scenarios"           # default
telegraf_conf = "./telegraf.conf"       # default
interval = "5s"                         # default

[application]
processes.docker = ["accuheat_client_db"]
processes.metal = ["accuheat_client"]

[scenario_runner]
cpu_tdp = 23

