//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::cpu::Entity as Cpu;
pub use super::iteration::Entity as Iteration;
pub use super::metrics::Entity as Metrics;
pub use super::power_curve::Entity as PowerCurve;
pub use super::run::Entity as Run;
