debug_level = "info"                                    # Optional - defaults to "info"
metrics_server_url = "http://cardamon.rootandbranch.io" # Optional - assumes local db if not specifed

[[processes]]
name = "db"                       # Required - must be unique among ALL processes
up = "docker compose up -d"       # Required
redirect.to = "file"              # Optional - values include "null" | "parent" | "file", defaults to "file"
process.type = "docker"
process.containers = ["postgres"] # Required

[[processes]]
name = "server"      # Required
up = "yarn dev"      # Required
redirect.to = "file" # Optional - values include "null" | "parent" | "file", defaults to "file"
type = "bare_metal"

[[scenarios]]
name = "basket_10" # Required
desc = "Adds ten items to the basket" # Optional 
command = "node ./scenarios/basket_10.js" # Required - commands for running scenarios
iterations = 1 # Optional - defaults to 1
processes = [
  "db",
  "server",
] # Required - prepend process name with `_` to ignore

[[observations]]
name = "checkout processes" # Required
scenarios = ["basket_10"]   # Required
