debug_level = "info"                                    # Optional - defaults to "info"
metrics_server_url = "http://cardamon.rootandbranch.io" # Optional - assumes local db if not specifed

[[processes]]
type = "docker"
name = "db"                      # Required - must be unique among ALL processes
containers = ["postgres"]        # Required
command = "docker compose up -d" # Required

[[processes]]
type = "bare_metal"
name = "server"      # Required
command = "yarn dev" # Required

[[scenarios]]
name = "basket_10" # Required
desc = "Adds ten items to the basket" # Optional 
command = "node ./scenarios/basket_10.js" # Required - commands for running scenarios
iterations = 1 # Optional - defaults to 1
processes = [
  "db",
  "server",
] # Required - prepend process name with `_` to ignore

[[observations]]
name = "checkout processes" # Required
scenarios = ["basket_10"]   # Required
