[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.5", features = ["json"] }
serde_json = "1.0.124"
tokio = { version = "1.37.0", features = ["full"] }

