services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly no
    networks:
      - app-network

  todo-app:
    build: .
    container_name: todo-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
