name: Release
permissions:
  "contents": "write"

on:
  pull_request:
  push:
    tags:
      - "**[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cardamon
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install NodeJS dependencies
        run: npm --prefix ui install

      - name: Build UI
        run: npm --prefix ui run build-only

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build Cardamon
        run: cargo build --release

      - name: Build release artifact
        run: |
          mkdir artifact
          cp target/release/cardamon artifact/cardamon
          cp LICENSE artifact/
          cp README.md artifact/

      - name: Compress build artifact
        run: tar -czf cardamon-x86_64-unknown-linux-gnu-${{ github.ref_name }}.tar.gz -C artifact .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: cardamon-x86_64-unknown-linux-gnu.tar.gz

  release:
    needs: [build_linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifact
          merge-multiple: true
      - name: Create release
        run: gh release create ${{  github.ref_name }} --draft --title "Release ${{ github.ref_name }}" --notes "" artifact/cardamon-*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
