[global]
debug_level = "info"


[[config]]
name = "test"
database_url = "test.db"
    [[config.scenario]]
    name = "Run py stress test"
    iterations = 2
    commands = [
        "python stress_client.py"
    ]


